#!/usr/bin/bash
set -e

xbps-install -y xcb-util-wm-devel xcb-util-keysyms-devel

git clone https://github.com/baskerville/bspwm.git
cd bspwm

make -j$(nproc)

cp -f bspwm bspc /usr/bin

cd ..
rm -r bspwm
