#!/usr/bin/bash
set -e

xbps-install -y \
wine \
winetricks \
python3 \
python3-cairo-devel \
gobject-introspection \
xdg-user-dirs \
xdg-utils \
git

rm -fr /tmp/grapejuice

sudo -u $SUDO_USER git clone https://gitlab.com/brinkervii/grapejuice.git /tmp/grapejuice

cd /tmp/grapejuice
#sudo -u $SUDO_USER ./install.py

