#!/usr/bin/bash
set -e

xbps-install -y linux-headers

aria2c https://us.download.nvidia.com/XFree86/Linux-x86_64/495.44/NVIDIA-Linux-x86_64-495.44.run -o nvidia.run

chmod +x nvidia.run
./nvidia.run

rm nvidia.run
