#!/usr/bin/bash
set -e

# Attempt git install
xbps-install -y git

# Clone the nvidia-patch repository
git clone https://github.com/keylase/nvidia-patch.git

# Run the patch
./nvidia-patch/patch-fbc.sh

# Remove the repository folder
rm -r nvidia-patch
