#!/bin/bash
#set -e
#xbps-install -y ncurses-devel
#wget https://github.com/Syllo/nvtop/archive/refs/tags/1.2.2.tar.gz
#tar xf 1.2.2.tar.gz
#cd nvtop-1.2.2
#mkdir build
#cd build
#cmake -DCMAKE_INSTALL_PREFIX=/usr ..
#make -j `nproc`
#make -j `nproc` install
#cd ../..
#rm -r nvtop-1.2.2
#rm 1.2.2.tar.gz
