#!/bin/bash
set -e

packages=(
	# files
	nnn
	nautilus
	rclone

	# steam
	steam
	glibc-32bit
	mesa-dri-32bit

	# general graphics
	mesa-dri
	mesa-vulkan-radeon
	vulkan-loader
	linux-firmware-amd

	wine
	winetricks

	# wayland
	wlr-randr
	river
	sway
	dmenu-wayland
	foot

	pulseaudio-utils
	htop
	radeontop

	# video/audio utilities
	deadbeef
	mpv
	pavucontrol
	ffmpeg
	yt-dlp

	# general utilities
	gimp
	lm_sensors
	firefox
	obs
	flameshot
	telegram-desktop
)

xbps-install -y void-repo-multilib void-repo-nonfree
xbps-install -yS ${packages[@]}
