#!/usr/bin/bash
set -e

packages=(
	# compilers/engines
	clang
	lld
	LuaJIT
	nodejs

	# headers/libraries
	SDL2-devel
	SDL2_image-devel
	SDL2_ttf-devel
	glfw-devel

	# files
	p7zip
	nnn
	autilus
	rclone

	# xorg
	xinit
	xorg-server
	xorg-input-drivers
	xorg-video-drivers
	xrandr

	# terminal emulator
	alacritty

	# video/audio utilities
	mpv
	ffmpeg
	deadbeef
	feh
	pavucontrol

	# general utilities
	gimp
	lm_sensors
	qrencode
	git
	firefox
	obs
	flameshot
	telegram-desktop
	aria2
)

xbps-install -y void-repo-nonfree
xbps-install -yS ${packages[@]}
