#!/usr/bin/bash
set -e

packages=(
	# compilers/engines
	clang
	lld
	LuaJIT
	nodejs

	# headers/libraries
	SDL2-devel

	# files
	nnn
	nautilus
	rclone

	# xorg
	xorg-input-drivers
	xorg-video-drivers

	# terminal emulator
	alacritty

	# video/audio utilities
	deadbeef
	feh
	pavucontrol

	# general utilities
	gimp
	lm_sensors
	firefox
	obs
	flameshot
	telegram-desktop
	aria2
)

xbps-install -y void-repo-nonfree
xbps-install -yS ${packages[@]}
