#!/bin/bash
set -e

packages=(
	# compilers/engines
	clang
	lld
	LuaJIT
	nodejs
	meson
	pkg-config
	cmake
	make
	gcc

	# headers/libraries
	SDL2-devel

	# files
	nnn
	nautilus
	rclone

	# steam
	steam
	glibc-32bit

	mesa
	mesa-dri

	mesa-32bit
	mesa-dri-32bit

	#nvidia-libs-32bit

	wine
	wine-32bit
	winetricks

	wlr-randr

	# xorg
	#xinit
	#xrandr
	#xorg-input-drivers
	#xorg-video-drivers
	#bspwm
	#sxhkd
	#dmenu

	pulseaudio-utils

	htop
	#intel-undervolt

	# terminal emulator
	alacritty

	# video/audio utilities
	deadbeef
	mpv
	#feh
	pavucontrol
	ffmpeg
	yt-dlp

	# general utilities
	gimp
	lm_sensors
	firefox

	obs
	obs-devel

	flameshot
	telegram-desktop
)

#xbps-install -y void-repo-nonfree void-repo-multilib void-repo-multilib-nonfree
#xbps-install -yS ${packages[@]}
