#!/usr/bin/sh

# Exit on failure
set -e

# Fetch latest steam debian package
aria2c https://cdn.akamai.steamstatic.com/client/installer/steam.deb

# DeDeb the package (installation)
dedeb steam_latest.deb

# Revert state
rm steam_latest.deb
