#!/usr/bin/bash
##################################################
# Voidy, by Jeffrey Skinner.                     #
# Voidy is personalized specifically for myself, #
# however feel free to use it as you'd like.     #
##################################################
set -e
cd $(dirname $0)

# Prerequisites
#./prereq/install

# Draggers
for module in drag/*
do
	cp $module /usr/bin
done

# Singles
for module in single/*
do
	./$module
done

# Contained
for module in contained/*/
do
	./$module/init
done

echo You did it, somehow
