#!/usr/bin/bash
##################################################
# Voidy, by Jeffrey Skinner.                     #
# Voidy is personalized specifically for myself, #
# however feel free to use it as you'd like.     #
##################################################

set -e
cd $(dirname $0)

order=(
	#getto
	#dedeb

	#nvidia

	#intel-undervolt

	#nvtop
	#nvdrm
	#nvidia-nvfbc

	#sazanami

	#packages

	#home

	#python

	#dedeb
	#steam

	#ytfetch
	#pipewire-pulse
	#wpa
	#bright
	#issue
	#grub-modifications
	#microcode

	#dmenu
	#bspwm
	#sxhkd
)

# Prerequisites
./prereqs/install

for module in drag/*
do
	cp module /usr/bin
done

for module in singles/*/
do
	./module
done

for module in contained/*/
do
	./module/init
done

echo All good
