#!/usr/bin/env bash
##################################################
# Voidy, by Jeffrey Skinner.                     #
# Voidy is personalized specifically for myself, #
# however feel free to use it as you'd like.     #
##################################################

set -e
cd $(dirname $0)

order=(
	home
	sazanami
	packages
	intel-undervolt
	steam
	nvtop
	ytfetch
	pipewire-pulse
	wpa
	bright
	nvidia-nvfbc
	issue
	grub-modifications
	microcode
	#grapejuice
)

for i in ${order[@]}
do
	echo $i: BEGIN
	./$i/install
	echo $i: END
done

echo REBOOT FOR CHANGES
