#!/bin/bash
##################################################
# Voidy, by Jeffrey Skinner.                     #
# Voidy is personalized specifically for myself, #
# however feel free to use it as you'd like.     #
##################################################
set -e
cd `dirname $0`

for module in scripts/*
do
	cp $module /bin
done

for module in group/*/
do
	./$module/install
done

for module in single/*
do
	./$module
done

echo good job
