#!/usr/bin/env sh
set -e
cd $(dirname $0)

xbps-install -y\
	git\
	libxml2-devel\
	autoconf\
	automake\
	libtool\
	gettext-devel

git clone https://github.com/aria2/aria2
cd aria2

autoreconf -i
./configure ARIA2_STATIC=yes
make

cd ..
#rm -r aria2
