#!/usr/bin/env sh

set -e
cd $(dirname $0)

xbps-install -y \
wine \
winetricks \
python3 \
python3-cairo-devel \
gobject-introspection \
xdg-user-dirs \
xdg-utils \
git


#rm -r /tmp/grapejuice

sudo -u $SUDO_USER git clone https://gitlab.com/brinkervii/grapejuice.git /tmp/grapejuice

cd /tmp/grapejuice
sudo -u $SUDO_USER ./install.py

