#!/usr/bin/env sh
set -e
cd $(dirname $0)

sudo aria2c https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/bin/yt-dlp
sudo chmod a+rx /usr/bin/yt-dlp

rm -r usr

cp ytfetch /usr/bin
