#!/bin/ash
set -e
cd $(dirname $0)

# Create a TTF folder in fonts
mkdir -p /usr/share/fonts/TTF

# Extract the font archive
tar xf sazanami-20040629.tar.bz2

# Copy the fonts into user fonts
cp sazanami-20040629/*.ttf /usr/share/fonts/TTF

# Remove the folder
rm -r sazanami-20040629
