[theme]
name = "native"
[theme.overrides]
idle_bg = "#000000"
idle_fg = "#c0c0c0"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 30
format = "%a %d/%m %R"
