#!/usr/bin/bash
# Bright by Blocksrey
set -e

gap=5
path=/sys/class/backlight/nvidia_0/brightness

state=$(cat $path)
state=${state#*.}

[[ $1 == + ]] && state=$((state+gap))
[[ $1 == - ]] && state=$((state-gap))

[[ $state -gt 100 ]] && state=100
[[ $state -lt   0 ]] && state=0

echo $state > $path
