#!/bin/sh

sxhkd &

feh --bg-center ~/.config/jp.jpg

bspc config border_width 0
bspc config window_gap   8

#bspc config focused_border_color "#ffffff"
#bspc config active_border_color "#d05353"
#bspc config normal_border_color "#f1e8b8"

bspc config pointer_motion_interval 30
