#!/bin/bash

xrandr --setprovideroutputsource 1 0
xrandr --output HDMI-A-1-0 --mode 1920x1080 --rate 144

pgrep -x sxhkd > /dev/null || sxhkd &
pipewire &

bspc monitor -d 0 1 2 3 4 5 6 7 8 9
bspc config border_width 0
bspc config window_gap 0
bspc config pointer_motion_interval 30

feh --bg-center ~/.wallpaper/jp.jpg
