#!/usr/bin/dash
# HarfBuzz Builder

# Exit on errors
set -e

# Make build directory
mkdir build
cd build

# Configure? idk
meson\
	--prefix=/usr\
	--buildtype=release\
	-Dgraphite2=enabled

# Install
ninja install -j$(nproc)
