#!/usr/bin/bash
set -e



xbps-install -y libdrm-devel llvm byacc flex libXfixes-devel libXrandr-devel



aria2c http://xmlsoft.org/sources/libxml2-2.9.12.tar.gz
tar xf libxml2-2.9.12.tar.gz
cd libxml2-2.9.12
../libxml2
cd ..
rm -r libxml2-2.9.12
rm libxml2-2.9.12.tar.gz



git clone https://gitlab.freedesktop.org/wayland/wayland.git
cd wayland
meson build --prefix=/usr --buildtype=release -Ddocumentation=false
ninja -C build -j$(nproc)
ninja install  -C build -j$(nproc)

cd ..
rm wayland -r



git clone https://gitlab.freedesktop.org/wayland/wayland-protocols.git
cd wayland-protocols
meson build --prefix=/usr --buildtype=release
ninja -C build -j$(nproc)
ninja install -C build -j$(nproc)

cd ..
rm wayland-protocols -r
