#!/usr/bin/bash
set -e



#libdrm-devel libXfixes-devel libXrandr-devel
xbps-install -y llvm byacc flex



aria2c http://xmlsoft.org/sources/libxml2-2.9.12.tar.gz
tar xf libxml2-2.9.12.tar.gz
cd libxml2-2.9.12
../libxml2
cd ..
rm libxml2-2.9.12 -r
rm libxml2-2.9.12.tar.gz



aria2c https://github.com/libexpat/libexpat/releases/download/R_2_4_2/expat-2.4.2.tar.gz
tar xf expat-2.4.2.tar.gz
cd expat-2.4.2
../expat
cd ..
rm expat-2.4.2 -r
rm expat-2.4.2.tar.gz



git clone https://gitlab.freedesktop.org/wayland/wayland.git
cd wayland
meson build --prefix=/usr --buildtype=release -Ddocumentation=false
ninja -C build -j$(nproc)
ninja install  -C build -j$(nproc)

cd ..
rm wayland -r



git clone https://gitlab.freedesktop.org/wayland/wayland-protocols.git
cd wayland-protocols
meson build --prefix=/usr --buildtype=release
ninja -C build -j$(nproc)
ninja install -C build -j$(nproc)

cd ..
rm wayland-protocols -r
