#!/bin/bash
set -e
cd $(dirname $0)

cp wpa_supplicant.conf /etc/wpa_supplicant
wpa_passphrase $1 $2 >> /etc/wpa_supplicant/wpa_supplicant.conf

ln -sf /usr/share/dhcpcd/hooks/10-wpa_supplicant /usr/libexec/dhcpcd-hooks
#ln -sf /etc/sv/dhcpcd /var/service